### PR TITLE
Testing Prototype

### LINKED ISSUE #13: Testing framework
Create basic tests that can be run on the code to ensure correctness. Likely blocked on having some actual code (so like #2), but could make some more code to just test on.

### PR DESCRIPTION
**Pull request by Soreloser2**
Fixes #13 
Adds some basic tests to the `test` folder. Requires Node.js with Puppeteer installed.
Steps to run (from repo directory):
1. Install Node.js online
2. `npm i puppeteer`
3. `node test/test.js`

Adding Tests:
Create new file/within test.js (will need to discuss, see #27)
write something like:
```
test('test description', async (t) => {
    // set up test if needed
    assert.strictEqual(someActual, someExpected, "error message");
})
```

### CODE REVIEW

**Review by paulstn — CHANGES_REQUESTED** [review]
It seems like package-lock.json is an automatically generated file, created by node.js. I don't believe we should have generated code be inside of our source control, so it's probably a good idea to write it in within the .gitignore.

**Comment by Soreloser2** [comment]
It is auto-generated, but it is listing all the dependencies so that node can automatically know what to include. It seems like the [suggestion from npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json) is to have this in the repo so that node knows the dependencies for every project.

The bulk of the actual dependencies, in `node_modules`, is in the `.gitignore`

**Review by paulstn — APPROVED** [review]
LGTM!

**Review by riteshsb — APPROVED** [review]

**Comment by kashish-ops** [comment]
lgtm!

**Pull request merged**
