### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by Soreloser2**
Adds a simple test for code quality and known security flaws

### CODE REVIEW

**Comment by Soreloser2** [comment]
This should be ready to go in now. It doesn't do much currently, just analyzes the limited code we have for known quality issues. I'm not sure if it failing actually prevents the PR from merging, @paulstn it's probably a setting close to where the number of reviewers requirement was if we would want to set it.

**Review by paulstn — APPROVED** [review]
LGTM!

**Comment by paulstn** [comment]
> This should be ready to go in now. It doesn't do much currently, just analyzes the limited code we have for known quality issues. I'm not sure if it failing actually prevents the PR from merging, @paulstn it's probably a setting close to where the number of reviewers requirement was if we would want to set it.

I just checked, the option is enabled but I have to manually set checks to be able to require passing before merges. We can only do that if it's within main, so we have to merge this first.

**Review by kashish-ops — APPROVED** [review]
Lgtm

**Pull request merged**
